// flow-typed signature: 40a440c8c72612f091ed47bc410096c2
// flow-typed version: <<STUB>>/chrome-promise_v^2.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrome-promise/chrome-promise' {
  declare module.exports: any;
}

declare module 'chrome-promise/e2e/spec' {
  declare module.exports: any;
}

declare module 'chrome-promise/protractor.conf' {
  declare module.exports: any;
}

declare module 'chrome-promise/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrome-promise/chrome-promise.js' {
  declare module.exports: $Exports<'chrome-promise/chrome-promise'>;
}
declare module 'chrome-promise/e2e/spec.js' {
  declare module.exports: $Exports<'chrome-promise/e2e/spec'>;
}
declare module 'chrome-promise/protractor.conf.js' {
  declare module.exports: $Exports<'chrome-promise/protractor.conf'>;
}
declare module 'chrome-promise/test/test.js' {
  declare module.exports: $Exports<'chrome-promise/test/test'>;
}
