// flow-typed signature: 92290fd9852580e0c63a51b89fc0f6af
// flow-typed version: <<STUB>>/ekko-lightbox_v^5.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ekko-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ekko-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ekko-lightbox/dist/ekko-lightbox' {
  declare module.exports: any;
}

declare module 'ekko-lightbox/dist/ekko-lightbox.min' {
  declare module.exports: any;
}

declare module 'ekko-lightbox/ekko-lightbox' {
  declare module.exports: any;
}

declare module 'ekko-lightbox/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ekko-lightbox/dist/ekko-lightbox.js' {
  declare module.exports: $Exports<'ekko-lightbox/dist/ekko-lightbox'>;
}
declare module 'ekko-lightbox/dist/ekko-lightbox.min.js' {
  declare module.exports: $Exports<'ekko-lightbox/dist/ekko-lightbox.min'>;
}
declare module 'ekko-lightbox/ekko-lightbox.js' {
  declare module.exports: $Exports<'ekko-lightbox/ekko-lightbox'>;
}
declare module 'ekko-lightbox/Gruntfile.js' {
  declare module.exports: $Exports<'ekko-lightbox/Gruntfile'>;
}
