// flow-typed signature: 918ef34a0ca236753d1e63ef30c08221
// flow-typed version: <<STUB>>/gulp-clean_v^0.3.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-clean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-clean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-clean/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-clean/index' {
  declare module.exports: $Exports<'gulp-clean'>;
}
declare module 'gulp-clean/index.js' {
  declare module.exports: $Exports<'gulp-clean'>;
}
declare module 'gulp-clean/test.js' {
  declare module.exports: $Exports<'gulp-clean/test'>;
}
