// flow-typed signature: 9a74bb61ac1d917c3ca1b34296216bb6
// flow-typed version: <<STUB>>/gulp-subtree_v^0.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-subtree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-subtree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-subtree/index' {
  declare module.exports: $Exports<'gulp-subtree'>;
}
declare module 'gulp-subtree/index.js' {
  declare module.exports: $Exports<'gulp-subtree'>;
}
