// flow-typed signature: 7575d6ee9e1cdbc43abcec1f0392105c
// flow-typed version: <<STUB>>/gulp-build-branch_v^0.1.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-build-branch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-build-branch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-build-branch/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-build-branch/src/index.js' {
  declare module.exports: $Exports<'gulp-build-branch/src/index'>;
}
