// flow-typed signature: a6a1e0ceca37c3c8ef641993c1bf69b9
// flow-typed version: <<STUB>>/gulp-react_v^3.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-react/index' {
  declare module.exports: $Exports<'gulp-react'>;
}
declare module 'gulp-react/index.js' {
  declare module.exports: $Exports<'gulp-react'>;
}
