// flow-typed signature: ca262770ceaf549eb25511aa7a4af292
// flow-typed version: <<STUB>>/gulp-html-tag-include_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-html-tag-include'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-html-tag-include' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-html-tag-include/references.all' {
  declare module.exports: any;
}

declare module 'gulp-html-tag-include/test/testreg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-html-tag-include/index' {
  declare module.exports: $Exports<'gulp-html-tag-include'>;
}
declare module 'gulp-html-tag-include/index.js' {
  declare module.exports: $Exports<'gulp-html-tag-include'>;
}
declare module 'gulp-html-tag-include/references.all.js' {
  declare module.exports: $Exports<'gulp-html-tag-include/references.all'>;
}
declare module 'gulp-html-tag-include/test/testreg.js' {
  declare module.exports: $Exports<'gulp-html-tag-include/test/testreg'>;
}
