// flow-typed signature: 6f15b788cc4b9206acdc03280eb04375
// flow-typed version: <<STUB>>/memwatch-next_v^0.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memwatch-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'memwatch-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memwatch-next/examples/basic_heapdiff' {
  declare module.exports: any;
}

declare module 'memwatch-next/examples/do_nothing_server' {
  declare module.exports: any;
}

declare module 'memwatch-next/examples/slightly_leaky' {
  declare module.exports: any;
}

declare module 'memwatch-next/include' {
  declare module.exports: any;
}

declare module 'memwatch-next/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memwatch-next/examples/basic_heapdiff.js' {
  declare module.exports: $Exports<'memwatch-next/examples/basic_heapdiff'>;
}
declare module 'memwatch-next/examples/do_nothing_server.js' {
  declare module.exports: $Exports<'memwatch-next/examples/do_nothing_server'>;
}
declare module 'memwatch-next/examples/slightly_leaky.js' {
  declare module.exports: $Exports<'memwatch-next/examples/slightly_leaky'>;
}
declare module 'memwatch-next/include.js' {
  declare module.exports: $Exports<'memwatch-next/include'>;
}
declare module 'memwatch-next/tests.js' {
  declare module.exports: $Exports<'memwatch-next/tests'>;
}
