/*
 * constants for managing tab window Flux store
 */
'use strict';

var constants = {
  ADD_TAB_WINDOWS: "ADD_TAB_WINDOWS",
  ATTACH_CHROME_WINDOW: "ATTACH_CHROME_WINDOW",
  CLOSE_TAB_WINDOW: "CLOSE_TAB_WINDOW",
  REMOVE_TAB_WINDOW: "REMOVE_TAB_WINDOW",
  REMOVE_CHROME_WINDOW: "REMOVE_CHROME_WINDOW",
  REPLACE_WINDOW_STATE: "REPLACE_WINDOW_STATE",
  REVERT_TAB_WINDOW: "REVERT_TAB_WINDOW",
  SYNC_WINDOW_LIST: "SYNC_WINDOW_LIST",
  SYNC_CHROME_WINDOW: "SYNC_CHROME_WINDOW",
  WINDOW_FOCUS_CHANGED: "WINDOW_FOCUS_CHANGED",
  TAB_CREATED: "TAB_CREATED",
  TAB_REMOVED: "TAB_REMOVED",
  TAB_UPDATED: "TAB_UPDATED",
  TAB_MOVED: "TAB_MOVED",
  TAB_DETACHED: "TAB_DETACHED",
  TAB_ATTACHED: "TAB_ATTACHED",
  TAB_ACTIVATED: "TAB_ACTIVATED"
};

export default constants;