/*
 * constants for managing tab window Flux store
 */
'use strict';

var constants = {
  ADD_TAB_WINDOWS: "ADD_TAB_WINDOWS",
  ATTACH_CHROME_WINDOW: "ATTACH_CHROME_WINDOW",
  CLOSE_TAB_WINDOW: "CLOSE_TAB_WINDOW",
  REMOVE_TAB_WINDOW: "REMOVE_TAB_WINDOW",
  REPLACE_WINDOW_STATE: "REPLACE_WINDOW_STATE",
  REVERT_TAB_WINDOW: "REVERT_TAB_WINDOW",
  SYNC_WINDOW_LIST: "SYNC_WINDOW_LIST",
  CHROME_WINDOW_CREATED: "CHROME_WINDOW_CREATED",
  CHROME_WINDOW_REMOVED: "CHROME_WINDOW_REMOVED",
  CHROME_WINDOW_FOCUS_CHANGED: "CHROME_WINDOW_FOCUS_CHANGED",
  CHROME_TAB_CREATED: "CHROME_TAB_CREATED",
  CHROME_TAB_REMOVED: "CHROME_TAB_REMOVED",
  CHROME_TAB_UPDATED: "CHROME_TAB_UPDATED",
  CHROME_TAB_MOVED: "CHROME_TAB_MOVED",
  CHROME_TAB_DETACHED: "CHROME_TAB_DETACHED",
  CHROME_TAB_ATTACHED: "CHROME_TAB_ATTACHED",
  CHROME_TAB_ACTIVATED: "CHROME_TAB_ACTIVATED",
  CHROME_TAB_REPLACED: "CHROME_TAB_REPLACED"
};

export default constants;